[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "gurobipy>=12.0.3",
    "matplotlib>=3.10.5",
    "numpy>=2.3.2",
    "streamlit>=1.48.0",
]
